# NumPy Tutorial: Basics

Welcome to the Basics NumPy tutorial. In this section, we will cover the fundamentals of NumPy, including array creation, array attributes, and basic operations. Let's dive into the world of NumPy, a powerful library for numerical computing in Python.


In [12]:
# Importing NumPy
import numpy as np

# Creating a simple NumPy array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", array_1d)

1D Array:
 [1 2 3 4 5]


## Array Attributes

NumPy arrays come with several attributes that describe their layout and properties. Let's explore some of these attributes.


In [13]:
# Exploring array attributes
print("Array Shape:", array_1d.shape)
print("Array Dimension:", array_1d.ndim)
print("Array Data Type:", array_1d.dtype)
print("Array Size:", array_1d.size)


Array Shape: (5,)
Array Dimension: 1
Array Data Type: int32
Array Size: 5


## Basic Operations

NumPy provides a wide range of mathematical operations. These operations can be performed element-wise, making them very efficient and convenient.


In [14]:
# Basic mathematical operations
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Addition
print("Array + 2:\n", array_2d + 2)

# Multiplication
print("Array * 3:\n", array_2d * 3)


Array + 2:
 [[3 4 5]
 [6 7 8]]
Array * 3:
 [[ 3  6  9]
 [12 15 18]]


## Indexing and Slicing

Accessing elements and subarrays is straightforward with NumPy, using indexing and slicing.

In [15]:
# Indexing and slicing
print("First row:", array_2d[0])
print("Second element of first row:", array_2d[0, 1])
print("Last column:\n", array_2d[:, -1])

First row: [1 2 3]
Second element of first row: 2
Last column:
 [3 6]


## Broadcasting

Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations.


In [16]:
# Broadcasting example
array_small = np.array([1, 2, 3])
array_large = np.array([[0], [10], [20], [30]])

# Broadcasting allows these arrays of different shapes to be added together
broadcast_result = array_large + array_small
print("Broadcast Result:\n", broadcast_result)


Broadcast Result:
 [[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


## Advanced Indexing

NumPy offers more sophisticated techniques for indexing, such as boolean indexing and fancy indexing, allowing for more complex data retrieval.


In [17]:
# Boolean indexing
array_data = np.array([1, -1, -2, 3, -3, 2])
positive_data = array_data[array_data > 0]
print("Positive elements:", positive_data)

# Fancy indexing
array_fancy = np.arange(10)
indices = [2, 5, 7]
selected_elements = array_fancy[indices]
print("Selected elements:", selected_elements)

Positive elements: [1 3 2]
Selected elements: [2 5 7]


## Manipulating Array Shapes

Reshaping arrays is a common operation in NumPy, enabling the reorganization of data for various computational needs.


In [18]:
# Reshaping an array
array_original = np.arange(6)
array_reshaped = array_original.reshape((2, 3))
print("Original array:", array_original)
print("Reshaped array:\n", array_reshaped)

# Transposing an array
array_transposed = array_reshaped.T
print("Transposed array:\n", array_transposed)


Original array: [0 1 2 3 4 5]
Reshaped array:
 [[0 1 2]
 [3 4 5]]
Transposed array:
 [[0 3]
 [1 4]
 [2 5]]


This concludes our NumPy tutorial, where we explored from the basic to more advanced features of NumPy. With these capabilities, you can tackle a wide range of mathematical and scientific computing tasks in Python.
